set(gcf, 'color', 'w', ...
    'defaultAxesFontSize', 20, ...) 
    'defaultlinelinewidth',2, ...
    'position', [0, 0, 100*get(gcf, 'papersize')], ...
    'paperposition', [0, 0, get(gcf, 'papersize')])
